Repository blue-build/cli, pull requests merged in 2024-03, with the labels that each got.

#109 feat: add flakehub entry + nix flake
  .envrc
  .github/workflows/flakehub-tagged.yml
  .gitignore
  README.md
  flake.lock
  flake.nix
Labels: enhancement

#110 fix: use container skopeo
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  recipe/Cargo.toml
  recipe/src/lib.rs
  recipe/src/recipe.rs
  src/commands/build.rs
  src/commands/template.rs
  src/globals.rs
  src/image_inspection.rs
  src/lib.rs
  src/strategies.rs
  src/strategies/buildah_strategy.rs
  src/strategies/credentials.rs
  src/strategies/docker_strategy.rs
  src/strategies/podman_api_strategy.rs
  src/strategies/podman_strategy.rs
  src/strategies/skopeo_strategy.rs
  template/src/lib.rs
  template/templates/Containerfile.j2
  utils/src/constants.rs
Labels: type: bug

#135 fix: Allow user supplied registry to be set in the template
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  src/commands/template.rs
  template/src/lib.rs
  template/templates/Containerfile.j2
Labels: type: bug

#139 feat: Improve logging output
  Cargo.lock
  Cargo.toml
  src/bin/bluebuild.rs
  src/commands/bug_report.rs
  src/commands/build.rs
  template/templates/modules/modules.j2
  utils/Cargo.toml
  utils/src/lib.rs
  utils/src/logging.rs
Labels: type: feature
